# Generated by Django 6.0.3 on 2026-03-25 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('trips', '0002_alter_trip_status'), ('trips', '0003_booking_trip_travellers'), ('trips', '0004_remove_booking_payments_remove_payment_trip_and_more'), ('trips', '0005_step_details_trip_details')]

    dependencies = [
        ('trips', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='travellers',
            field=models.ManyToManyField(null=True, related_name='trips', through='trips.Booking', to='users.profile'),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='trip',
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='trips.booking'),
        ),
        migrations.AddField(
            model_name='step',
            name='details',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='details',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
