# Generated by Django 6.0.3 on 2026-03-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('transfer', 'Transfer'), ('debit_card', 'Debit Card'), ('cash', 'Cash')], default='credit_card', max_length=20),
        ),
    ]
