# Generated by Django 6.0.3 on 2026-03-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_status_squashed_0005_step_details_trip_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='type',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternnon', 'Afternoon'), ('evening', 'Evening'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('breakfast', 'Breakfast')]),
        ),
    ]
